import { User } from 'models';

export const userTableMock: User[] = [
  {
    id: '1',
    username: 'admin',
    password: 'demo',
    email: 'admin@demo.com',
    authToken: 'auth-token-8f3ae836da744329a6f93bf20594b5cc',
    firstname: 'Nguyen',
    lastname: 'Viet Cuong',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '2',
    username: 'user',
    password: 'demo',
    email: 'user@demo.com',
    authToken: 'auth-token-6829bba69dd3421d8762-991e9e806dbf',
    firstname: 'Adam',
    lastname: 'Johnson',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '3',
    username: 'guest',
    password: 'demo',
    email: 'guest@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Cristiano',
    lastname: 'Ronaldo',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '4',
    username: 'ozilMesut',
    password: 'demo',
    email: 'ozilMesut@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Mesut',
    lastname: 'Ozil',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '5',
    username: 'berndLeno',
    password: 'demo',
    email: 'berndLeno@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Bernd',
    lastname: 'Leno',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '6',
    username: 'hectorBellerin',
    password: 'demo',
    email: 'hectorBellerin@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Hector',
    lastname: 'Bellerin',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '8',
    username: 'granit',
    password: 'demo',
    email: 'granit@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Granit',
    lastname: 'Xhaka',
    createdBy: 'admin',
    isDisabled: true,
    createdDate: '10-08-2021',
  },
  {
    id: '9',
    username: 'alexander',
    password: 'demo',
    email: 'alexander@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Alexander',
    lastname: 'Lacazette',
    createdBy: 'admin',
    isDisabled: true,
    createdDate: '10-08-2021',
  },
  {
    id: '10',
    username: 'nicolas',
    password: 'demo',
    email: 'nicolas@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Nicolas',
    lastname: 'Pepe',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '11',
    username: 'alexis',
    password: 'demo',
    email: 'alexis@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Alexis',
    lastname: 'Sanchez',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
  {
    id: '12',
    username: 'aron',
    password: 'demo',
    email: 'aron@demo.com',
    authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
    firstname: 'Aron',
    lastname: 'Ramsey',
    createdBy: 'admin',
    isDisabled: false,
    createdDate: '10-08-2021',
  },
];
